### ISSUE TITLE
[codestyle] Reading files via context manager semantic in python

### ISSUE THREAD

**Issue by sir-chaos** [dvolkow/MLE#5]
In mle_io.py:
```
f = open(DATASET_FILE, 'r')
reader = csv.reader(f)
#reading
```
In modern python you'd rather use context manager semantics:
```
with open(DATASET_FILE, 'r') as f:
    reader = csv.reader(f)
   #reading
```
This is better due to automatic cleanup in any case after leaving the `with` scope.

I will mark non-critical issues as [codestyle], as there are no issue labels defined in the repo (or I can't assign one).

**Comment by dvolkow** [comment]
https://github.com/dvolkow/MLE/pull/11
