### ISSUE TITLE
[codestyle] Debug output in minimize()

### ISSUE THREAD

**Issue by sir-chaos** [dvolkow/MLE#7]
'minimize' function you use supports the 'callback' argument it calls after each iteration, you can insert debug output there.
The difference with what you did is that it is called only after each _full_ iteration; the likelyhood_log function, on the other hand, is called many times per iteration (every time minimizer needs _any_ value for calculations, say, it's called multiple times only to numerically calculate a singe derivative value).

**Comment by dvolkow** [comment]
https://github.com/dvolkow/MLE/pull/12
