### ISSUE TITLE
numpy usage

### ISSUE THREAD

**Issue by sir-chaos** [dvolkow/MLE#9]
Generally, numpy is much faster then python native arrays (altho in this case I didn't achieve significant speed-up by merely using numpy everywhere).

Numpy lets you to carry operations on whole arrays (much like in R):

```
vr = vr_calc_all(R_0, A) + v_sun_all(u, v, w) # this is array already

sigma = stdev(vr)

L     = - len(data.l) * math.log(math.sqrt(2 * math.pi) * sigma)
vr_diff = vr - data.vr
vr_diff_sqr = np.power(vr_diff, 2)
L -= np.sum(vr_diff_sqr) / (2 * sigma ** 2)

```

I also changed lists to numpy arrays everywhere to achieve array-wise operations, like:

```
def r_all(self, r0):
    if r0 != self.cached_value[0]:
        r0s = np.repeat(r0, self.distcos.shape[0])
        self.cached_value = (r0, np.sqrt(np.power(r0s, 2) + self.distcos - self.dblcos * r0))
    return self.cached_value[1]

```

**Comment by sir-chaos** [comment]
edit: I changed the last non-numpy function stdev(vr) to np.std(), and the calculations sped up by several orders of magnitude. Also, The result changed a bit, and now minimize reports success instead of failure.
```
    vr = vr_calc_all(R_0, A) + v_sun_all(u, v, w)

    sigma = np.std(vr)
    L     = - len(data.l) * math.log(math.sqrt(2 * math.pi) * sigma)
    vr_diff = vr - data.vr
    vr_diff_sqr = np.power(vr_diff, 2)
    L -= np.sum(vr_diff_sqr) / (2 * sigma ** 2)

    return -L
```

**Comment by dvolkow** [comment]
https://github.com/dvolkow/MLE/pull/11
